"""
RegLens Regulatory Document Ingestion CLI

Usage:
    python -m ingestion.ingest --path ./data --recursive
    python -m ingestion.ingest --path ./data/adb_brief.txt
    python -m ingestion.ingest --path ./data --recursive --skip-extraction

Parsing hierarchy (ingestion/parser.py):
    LlamaParse (cloud, if LLAMA_CLOUD_API_KEY set) → Docling (local) → read_text

Design (Ketchup DEV session):
    - UUIDs generated by application
    - No FK constraints — link tables inserted explicitly
    - Status updated by application
    - document.metadata JSONB populated by LLM extraction (enables adaptivity)
"""
from __future__ import annotations
import os, json, asyncio, argparse, hashlib
from pathlib import Path
from uuid import uuid4

import asyncpg
from openai import AsyncOpenAI
from dotenv import load_dotenv

load_dotenv()

from .chunker   import chunk_document
from .embedder  import embed_chunks
from .extractor import extract_document_metadata
from .parser    import parse_document, SUPPORTED_EXTENSIONS


def new_uid() -> str:
    return str(uuid4())


def vector_literal(embedding: list[float]) -> str:
    """pgvector text literal — cast with ::vector in SQL."""
    return "[" + ",".join(f"{v:.8f}" for v in embedding) + "]"


def file_sha256(file_path: Path) -> str:
    """Hash the raw file bytes — cheap duplicate detection without parsing."""
    h = hashlib.sha256()
    with open(file_path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


async def _connect() -> asyncpg.Connection:
    """
    Fresh short-lived connection for DB writes. Parsing a large PDF can
    take minutes — a connection opened before parsing gets dropped by
    Neon's pooler as idle, so each document connects only when it is
    ready to write.
    """
    return await asyncpg.connect(
        os.environ["DATABASE_URL"],
        statement_cache_size=0,   # required behind Neon's pgbouncer pooler
    )


async def ingest_file(
    file_path:        Path,
    embedding_client: AsyncOpenAI,
    llm_client:       AsyncOpenAI,
    skip_extraction:  bool = False,
) -> str:
    """
    Ingest a single regulatory document.
    Returns document_uid, "skipped" if already ingested (same file hash),
    or empty string on failure.
    Opens its own short-lived DB connections so long parses never hold one.
    """
    if file_path.suffix.lower() not in SUPPORTED_EXTENSIONS:
        print(f"[skip] {file_path.name} — unsupported file type")
        return ""

    # === Duplicate check BEFORE parsing (file-byte hash — no parse cost) ===
    content_hash = file_sha256(file_path)
    conn = await _connect()
    try:
        existing = await conn.fetchval(
            """
            SELECT document_uid FROM document
            WHERE status = 'active' AND metadata->>'file_hash' = $1
            """,
            content_hash,
        )
    finally:
        await conn.close()
    if existing:
        print(f"[skip] {file_path.name} — already ingested (identical file hash)")
        return "skipped"

    # Parse document — hierarchy: LlamaParse → Docling → plain text
    content = await parse_document(file_path)

    if len(content.split()) < 50:
        print(f"[skip] {file_path.name} — too short or unreadable (<50 words)")
        return ""

    title        = file_path.stem.replace("_", " ").replace("-", " ").title()
    document_uid = new_uid()

    # === Step 1: Extract regulatory metadata via LLM (enables corpus adaptivity) ===
    if skip_extraction:
        metadata = {"regulatory_body": "Unknown", "domain": "general",
                    "document_type": "unknown", "regulatory_level": "unknown",
                    "obligations_present": False}
    else:
        print(f"[extract] {file_path.name}...")
        metadata = await extract_document_metadata(llm_client, content, file_path.name)

    metadata["file_name"]   = file_path.name
    metadata["source_path"] = str(file_path)
    metadata["file_hash"]   = content_hash

    # === Step 2: Chunk the document (before touching the DB) ===
    chunks = chunk_document(content, chunk_size=800, overlap=150)
    if not chunks:
        print(f"[skip] {file_path.name} — no valid chunks")
        return ""

    # === Step 3: Embed chunks (still no DB connection held) ===
    embeddings = await embed_chunks(embedding_client, chunks)

    chunk_rows = []
    link_rows  = []
    for i, (chunk_text, emb) in enumerate(zip(chunks, embeddings)):
        chunk_uid = new_uid()
        chunk_rows.append((
            chunk_uid,
            f"{title} — chunk {i + 1}",
            chunk_text,
            vector_literal(emb),
            i,
            len(chunk_text.split()),
            json.dumps({
                "regulatory_body": metadata.get("regulatory_body"),
                "domain":          metadata.get("domain"),
            }),
        ))
        # Link row — document_chunk (no FK)
        link_rows.append((document_uid, chunk_uid))

    # === Step 4: All DB writes on one fresh connection ===
    conn = await _connect()
    try:
        await conn.execute(
            """
            INSERT INTO document
                (document_uid, description, source, content,
                 source_type, status, metadata)
            VALUES ($1, $2, $3, $4, $5, 'active', $6)
            """,
            document_uid, title, str(file_path), content,
            metadata.get("document_type", "unknown"), json.dumps(metadata),
        )

        # Supersede older versions: match exact source path OR same
        # filename (protects against relative/absolute path differences)
        old_uids = [
            str(r["document_uid"]) for r in await conn.fetch(
                """
                SELECT document_uid FROM document
                WHERE (source = $1 OR source LIKE $2 OR metadata->>'file_name' = $3)
                  AND document_uid != $4
                """,
                str(file_path), f"%/{file_path.name}", file_path.name, document_uid,
            )
        ]
        for old_uid in old_uids:
            await conn.execute(
                """
                DELETE FROM chunk
                WHERE chunk_uid IN (
                    SELECT chunk_uid FROM document_chunk WHERE document_uid = $1
                )
                """,
                old_uid,
            )
            await conn.execute(
                "DELETE FROM document_chunk WHERE document_uid = $1", old_uid
            )
            await conn.execute(
                "DELETE FROM document WHERE document_uid = $1", old_uid
            )
        if old_uids:
            print(f"[ingest] superseded {len(old_uids)} older version(s) of {file_path.name}")

        await conn.executemany(
            """
            INSERT INTO chunk
                (chunk_uid, description, content, embedding,
                 chunk_index, token_count, status, metadata)
            VALUES ($1, $2, $3, $4::vector, $5, $6, 'active', $7)
            """,
            chunk_rows,
        )
        await conn.executemany(
            "INSERT INTO document_chunk (document_uid, chunk_uid) VALUES ($1, $2)",
            link_rows,
        )
    finally:
        await conn.close()

    print(
        f"[ingest] OK '{title}' | "
        f"{len(chunks)} chunks | "
        f"body={metadata.get('regulatory_body')} | "
        f"domain={metadata.get('domain')} | "
        f"uid={document_uid}"
    )
    return document_uid


async def ingest_document_async(
    document_uid:     str,
    file_path:        Path,
    embedding_client: AsyncOpenAI,
    llm_client:       AsyncOpenAI,
) -> None:
    """
    Finalize a document whose stub row (status='processing') already exists.
    Used by the upload endpoint's background task: parse -> extract -> chunk
    -> embed -> write chunks -> flip status to 'active' (or 'failed').

    On any failure the row is marked 'failed' with the error in metadata,
    so the UI can surface it instead of leaving a phantom 'processing' row.
    """
    try:
        content = await parse_document(file_path)
        if len(content.split()) < 50:
            raise ValueError("document too short or unreadable (<50 words)")

        title = file_path.stem.replace("_", " ").replace("-", " ").title()
        metadata = await extract_document_metadata(llm_client, content, file_path.name)
        metadata["file_name"]   = file_path.name
        metadata["source_path"] = str(file_path)
        metadata["file_hash"]   = file_sha256(file_path)

        chunks = chunk_document(content, chunk_size=800, overlap=150)
        if not chunks:
            raise ValueError("no valid chunks produced")

        embeddings = await embed_chunks(embedding_client, chunks)

        chunk_rows, link_rows = [], []
        for i, (chunk_text, emb) in enumerate(zip(chunks, embeddings)):
            chunk_uid = new_uid()
            chunk_rows.append((
                chunk_uid,
                f"{title} — chunk {i + 1}",
                chunk_text,
                vector_literal(emb),
                i,
                len(chunk_text.split()),
                json.dumps({
                    "regulatory_body": metadata.get("regulatory_body"),
                    "domain":          metadata.get("domain"),
                }),
            ))
            link_rows.append((document_uid, chunk_uid))

        conn = await _connect()
        try:
            await conn.executemany(
                """
                INSERT INTO chunk
                    (chunk_uid, description, content, embedding,
                     chunk_index, token_count, status, metadata)
                VALUES ($1, $2, $3, $4::vector, $5, $6, 'active', $7)
                """,
                chunk_rows,
            )
            await conn.executemany(
                "INSERT INTO document_chunk (document_uid, chunk_uid) VALUES ($1, $2)",
                link_rows,
            )
            await conn.execute(
                """
                UPDATE document
                SET description = $2, content = $3, source_type = $4,
                    metadata = $5, status = 'active'
                WHERE document_uid = $1
                """,
                document_uid, title, content,
                metadata.get("document_type", "unknown"), json.dumps(metadata),
            )
        finally:
            await conn.close()

        print(f"[ingest-async] OK '{title}' | {len(chunks)} chunks | uid={document_uid}")

    except Exception as e:
        print(f"[ingest-async] FAILED uid={document_uid}: {e}")
        conn = await _connect()
        try:
            await conn.execute(
                """
                UPDATE document
                SET status = 'failed',
                    metadata = metadata || jsonb_build_object('error', $2::text)
                WHERE document_uid = $1
                """,
                document_uid, str(e)[:500],
            )
        finally:
            await conn.close()


async def main(args) -> None:
    embedding_client = AsyncOpenAI(
        api_key=os.getenv("EMBEDDING_API_KEY", os.getenv("OPENAI_API_KEY", "")),
        base_url=os.getenv("EMBEDDING_BASE_URL", "https://api.openai.com/v1"),
    )
    llm_client = AsyncOpenAI(
        api_key=os.getenv("LLM_API_KEY", os.getenv("OPENAI_API_KEY", "")),
        base_url=os.getenv("LLM_BASE_URL", "https://api.openai.com/v1"),
    )

    path = Path(args.path)

    if path.is_file():
        files = [path]
    elif args.recursive:
        files = [f for f in path.rglob("*") if f.suffix.lower() in SUPPORTED_EXTENSIONS]
    else:
        files = [f for f in path.iterdir() if f.suffix.lower() in SUPPORTED_EXTENSIONS]

    files = sorted(files)
    print(f"\n[ingest] Found {len(files)} files to process")
    print(f"[ingest] Skip LLM extraction: {args.skip_extraction}\n")

    success, skipped, failed = 0, 0, 0
    for f in files:
        try:
            uid = await ingest_file(
                f, embedding_client, llm_client,
                skip_extraction=args.skip_extraction,
            )
        except Exception as e:
            print(f"[error] {f.name}: {e}")
            failed += 1
            continue
        if uid == "skipped":
            skipped += 1
        elif uid:
            success += 1
        else:
            failed += 1

    print(
        f"\n[ingest] Complete — {success} ingested, {skipped} skipped "
        f"(already present), {failed} failed, of {len(files)} files"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="RegLens regulatory document ingestion",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python -m ingestion.ingest --path ./data --recursive\n"
            "  python -m ingestion.ingest --path ./data/bon_determination.pdf\n"
            "  python -m ingestion.ingest --path ./data --skip-extraction\n"
            "\n"
            "Supports any regulatory document — examples:\n"
            "  SADC/African:\n"
            "    Bank of Namibia payment determinations\n"
            "    NAMFISA supervisory circulars\n"
            "    SARB / FSCA regulatory frameworks\n"
            "    ESAAMLG AML/CFT standards\n"
            "    SADC payment system oversight documents\n"
            "    COMESA cross-border payment guidelines\n"
            "    FATF Mutual Evaluation Reports for SADC members\n"
            "    African Development Bank financial sector guidance\n"
            "\n"
            "  Global:\n"
            "    FCA Handbook - EMIR - MiFIR - Basel III\n"
            "    FATF 40 Recommendations - BIS CPMI standards\n"
            "    Any national central bank circulars\n"
        ),
    )
    parser.add_argument("--path",             required=True,      help="File or directory path")
    parser.add_argument("--recursive",        action="store_true", help="Recurse into subdirectories")
    parser.add_argument("--skip-extraction",  action="store_true", help="Skip LLM metadata extraction (faster, less adaptive)")
    asyncio.run(main(parser.parse_args()))